#===----------------------------------------------------------------------===//
#
# Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
#===----------------------------------------------------------------------===//

[workspace]
members = [
    "flat_tlsf",
    "flat_tlsf2",
    "benches",
    "fuzz",
]
resolver = "2"

[profile.release]
lto = "thin"
codegen-units = 16
panic = "abort"
debug = true
