#include "baremetal_libc.h"

#define safe_printf printf

#define SHADOW_OFFSET 0x4000
#define MAPPING_MIN 0x20000000
#define MAPPING_MAX 0x20020000
#define MAPPING_SCALE 3
#define SHADOW_GRANULARITY (1 << MAPPING_SCALE)

#ifndef SPLIT_SHADOW
#define SPLIT_SHADOW
#endif
// #define ENABLE_MPU
#define REGISTER_GLOBALS
// #define SMALL_GLOBAL_METADATA

// TODO This is a lot of extra data per global generated by the compiler.
// Options:
// - Cut down the generated structs to just pointer and size. Calculate
//   red-zone size in a consistent way so we don't need to store that. Get rid
//   of the names and source locations. Do we need has_dynamic_init and
//   odr_indicator? Best case here is 2 pointers global, could maybe cut those
//   down to 32-bit for AArch64.
// - Generate the initial shadow memory at link-time. This will probably need
//   special linker support, it's unlilkely SHF_LINK_ORDER can accurately
//   represent the requirements of the shadow memory. Size is 1 byte per 8
//   bytes of globals (including shadow). This could be worse than option 1 for
//   large globals, but then RW data compression would be very effective.

// This structure describes an instrumented global variable.
struct __asan_global {
  uintptr_t beg;              // The address of the global.
  size_t size;                // The original size of the global.
#ifndef SMALL_GLOBAL_METADATA
  size_t size_with_redzone;   // The size with the redzone.
  const char *name;           // Name as a C string.
  const char *module_name;    // Module name as a C string. This pointer is a
                              // unique identifier of a module.
  uintptr_t has_dynamic_init; // Non-zero if the global has dynamic initializer.
  void *location; // Source location of a global, not used by LLVM
  void *odr_indicator; // The address of the ODR indicator symbol.
#endif
};

uint64_t getRedzoneSizeForGlobal(uint64_t SizeInBytes);

extern __asan_global __asan_global_metadata$$Base[];
extern __asan_global __asan_global_metadata$$Limit;

extern char Image$$ER_RW_ZI$$Base;
extern char Image$$ER_RW_ZI$$Limit;
extern char Image$$STACKHEAP_START$$Base;
extern char Image$$STACKHEAP_SPLIT$$Base;
extern char Image$$STACKHEAP_END$$Limit;

extern unsigned char __shadow_mem_start;
extern unsigned char __shadow_mem_end;
extern unsigned char Image$$ER_RO_DATA$$Base;
extern unsigned char Image$$ER_RO_DATA$$Limit;

enum MemoryClass {
  UNKNOWN,
  GLOBAL,
  ROM,
  STACK,
  HEAP,
  SHADOW,
};

// TODO This, and other references to linker-defined symbols, should be
// provided by the user, so we don't constrain their scatter files too much.
MemoryClass classify_memory(void *p) {
  if (p >= &Image$$ER_RW_ZI$$Base && p < &Image$$ER_RW_ZI$$Limit)
    return GLOBAL;
  else if (p >= &Image$$STACKHEAP_START$$Base &&
           p < &Image$$STACKHEAP_SPLIT$$Base)
    return HEAP;
  else if (p >= &Image$$STACKHEAP_SPLIT$$Base &&
           p < &Image$$STACKHEAP_END$$Limit)
    return STACK;
  else if (p >= &__shadow_mem_start && p < &__shadow_mem_end)
    return SHADOW;
  else if (p >= &Image$$ER_RO_DATA$$Base && p < &Image$$ER_RO_DATA$$Limit)
    return ROM;
  else
    return UNKNOWN;
}

// {{{ Stack trace
namespace {
const uintptr_t stack_low = (uintptr_t)&Image$$STACKHEAP_START$$Base;
const uintptr_t stack_high = (uintptr_t)&Image$$STACKHEAP_END$$Limit;

void print_stack_trace() {
  uintptr_t sp, pc;
  sp = (uintptr_t)__builtin_frame_address(0);
  asm("mov %0, pc" : "=r" (pc));
  printf("Stack trace:\n");
  int depth = 0;
  do {
    printf("  pc %#zx sp %#zx\n", pc, sp);
    pc = ((uintptr_t *)sp)[1];
    uintptr_t next_sp = ((uintptr_t *)sp)[0];
    if (next_sp <= sp)
      break;
    sp = next_sp;
  } while (++depth < 32 && !(pc == 0 || pc == 0xdfdfcfcf || pc == 0xdfdfdfdf ||
                             sp == 0 || sp < stack_low || sp > stack_high));
}

} // namespace
// }}}

namespace {

// {{{ Poisoning

#ifdef SPLIT_SHADOW
#define LOWER_SHADOW_SIZE 4096
unsigned char *get_shadow_addr(uintptr_t addr) {
  uintptr_t offset_in_region = addr & 0x0fffffff;
  uintptr_t upper_region_bit = addr & 0x20000000;
  intptr_t region_sign = (intptr_t)(upper_region_bit - 0x20000000);
  intptr_t effective_distance = (intptr_t)(region_sign + offset_in_region);
  intptr_t scaled_distance = effective_distance >> MAPPING_SCALE;
  uintptr_t effective_base = (0x20000000 + SHADOW_OFFSET + LOWER_SHADOW_SIZE);
  return (unsigned char *)(effective_base + scaled_distance);
}

uintptr_t get_normal_addr(void* shadow_addr) {
  return (uintptr_t)shadow_addr;
}
#else
unsigned char *get_shadow_addr(uintptr_t addr) {
  return (unsigned char *)((addr >> MAPPING_SCALE) + SHADOW_OFFSET);
}

uintptr_t get_normal_addr(void* shadow_addr) {
  return ((uintptr_t)shadow_addr - SHADOW_OFFSET) << MAPPING_SCALE;
}
#endif

void set_shadow_byte(uintptr_t ptr, unsigned char val) {
  *get_shadow_addr(ptr) = val;
}

uint8_t get_shadow_byte(uintptr_t ptr) {
  return *get_shadow_addr(ptr);
}

void poison_mem(uintptr_t ptr, size_t len, unsigned char poison_byte=0xff) {
  //safe_printf("poison %p, %zu, %#hhx\n", ptr, len, poison_byte);
  for (int i = 0; i < len; i += 8)
    set_shadow_byte(ptr + i, poison_byte);
}

void poison_mem_right_redzone(uintptr_t start, size_t len, size_t redzone_len, unsigned char redzone_byte=0xff) {
  //safe_printf("poison %p, %zu, %#hhx\n", ptr, len, poison_byte);
  assert((start % SHADOW_GRANULARITY) == 0);
  assert(((len + redzone_len) % SHADOW_GRANULARITY) == 0);
  if ((len % SHADOW_GRANULARITY) != 0) {
    set_shadow_byte((start + len) & ~7, (start + len) & 7);
  }
  for (int i = (start + len + 7) & ~7; i < (start + len + redzone_len); i += 8)
    set_shadow_byte(i, redzone_byte);
}

void unpoison_mem(uintptr_t ptr, size_t len, size_t redzone_len, unsigned char redzone_byte) {
  //safe_printf("unpoison %p+%zx, %zu byte redzone of %#hhx\n", ptr, len, redzone_len,
  //            redzone_byte);
  // Fully unpoisoned region
  for (int i = 0; i < (len & ~7); i += 8)
    set_shadow_byte(ptr + i, 0);

  // Partially-poisoned shadow byte
  if (len % 8 != 0)
    set_shadow_byte(ptr + (len & ~7), len % 8);

  // Rest of poisoned redzone
  for (int i = ((len + 7) & ~7); i < (len + redzone_len); i += 8)
    set_shadow_byte(ptr + i, redzone_byte);
}

// }}}

} // namespace

// {{{ Error reporting functions

namespace {

unsigned char * const shadow_low = &__shadow_mem_start;
unsigned char * const shadow_high = &__shadow_mem_end;

const char * shadow_byte_descriptions[16] = {
  // 0xf0
  "heap buffer overflow",
  "stack buffer overflow",
  "stack buffer overflow",
  "stack buffer overflow",
  // 0xf4
  nullptr,
  nullptr,
  nullptr,
  nullptr,
  // 0xf8
  nullptr,
  "global buffer overflow",
  nullptr,
  nullptr,
  // 0xfc
  nullptr,
  "heap use after free",
  nullptr,
  nullptr,
};

const char *shadow_byte_color(unsigned char shadow) {
  if (shadow < 8)
    return "\u001b[0m";
  else
    return "\u001b[31m";
}

void print_shadow_memory(uintptr_t addr) {
  uintptr_t shadow_addr = (uintptr_t)get_shadow_addr(addr);
  unsigned char *shadow_row_addr =
      (unsigned char *)(shadow_addr & ~0xf);
  for (int row_offset = -3; row_offset <= 3; ++row_offset) {
    unsigned char *this_shadow_row_addr = shadow_row_addr + row_offset * 16;
    if (classify_memory(this_shadow_row_addr) != SHADOW) {
      continue;
    }
    printf("%#010zx: ", get_normal_addr(this_shadow_row_addr));
    for (int column = 0; column < 16; ++column) {
      unsigned char shadow = *(this_shadow_row_addr + column);
      const char *before = ((uintptr_t)(this_shadow_row_addr + column) == shadow_addr) ? "[" : " ";
      const char *after = ((uintptr_t)(this_shadow_row_addr + column) == shadow_addr) ? "]" : " ";
      const char *color = shadow_byte_color(shadow);
      printf("%s%s%02x\u001b[0m%s", before, color, shadow, after);
    }
    printf("\n");
  }
}

void report_nearby_stuff_global(uintptr_t addr, size_t access_size) {
  for (__asan_global *g = &__asan_global_metadata$$Base[0];
       g < &__asan_global_metadata$$Limit; ++g) {
    if (addr >= g->beg && addr < (g->beg + g->size + getRedzoneSizeForGlobal(g->size))) {
#ifdef SMALL_GLOBAL_METADATA
      printf("Nearby global at %#zx, size %zd\n", g->beg, g->size);
#else
      printf("Nearby global '%s' at %#zx, size %zd (has_dynamic_init=%d)\n",
             g->name ? g->name : "(unknown)", g->beg, g->size, (int)g->has_dynamic_init);
#endif
    }
  }
}
void report_nearby_stuff_stack(uintptr_t addr) {
  uintptr_t access_addr = addr;

  // Round down to asan granule
  addr &= ~0x7;
  
  uintptr_t stack_base = (uintptr_t)&Image$$STACKHEAP_SPLIT$$Base;

  // Search downwards in memory for the stack left redzone.
  while (addr >= stack_base && get_shadow_byte(addr) != 0xf1) {
    addr -= 8;
  }

  // Keep searching until we leave the stack left redzone.
  while (addr >= stack_base && get_shadow_byte(addr) == 0xf1) {
    addr -= 8;
  }

  // Back up one granule.
  addr += 8;

  if (*(uintptr_t *)addr != 0x41b58ab3) {
    printf("Stack frame magic not found\n");
    return;
  }

  ptrdiff_t frame_offset = access_addr - addr;
  const char *frame_desc = ((const char **)addr)[1];
  uintptr_t frame_pc = ((uintptr_t *)addr)[2] & ~1;
  printf("Access is %#zx bytes into the stack frame starting at %#zx, created "
         "by the function at %#zx\n",
         frame_offset, addr, frame_pc);

  char *p;
  uintptr_t num_objs = strtoll(frame_desc, &p, 10);
  printf("Frame contains %zd objects:\n", num_objs);
  for (int n = 0; n < num_objs; ++n) {
    uintptr_t obj_addr = strtoll(p, &p, 10);
    uintptr_t obj_size = strtoll(p, &p, 10);
    uintptr_t name_len = strtoll(p, &p, 10);
    printf("  [%#zx,%#zx): %.*s\n", obj_addr, obj_addr + obj_size, name_len, p+1);
    p += name_len + 1;
  }
}
void report_nearby_stuff_heap(uintptr_t addr) {
  // TODO
}

void report_error(uintptr_t addr, size_t size, bool is_load, void *pc) {
  uint8_t shadow_byte = get_shadow_byte(addr);
  // If this is a partially-valid granule, check the next one to see what type
  // of poisoned memory we overflowed into.
  if (shadow_byte < 8)
    shadow_byte = get_shadow_byte(addr + 8);

  const char *description = nullptr;
  if (shadow_byte >= 0xf0)
    description = shadow_byte_descriptions[shadow_byte - 0xf0];

  if (description)
    printf("\u001b[31masan failure\u001b[0m, %s of %d bytes at %#" PRIxPTR
           ", PC=%#" PRIxPTR ": %s\n",
           (is_load ? "load" : "store"), size, addr, (uintptr_t)pc,
           description);
  else
    printf("\u001b[31masan failure\u001b[0m, %s of %d bytes at %#" PRIxPTR
           ", PC=%#" PRIxPTR ": %#02x\n",
           (is_load ? "load" : "store"), size, addr, (uintptr_t)pc,
           shadow_byte);
  print_stack_trace();
  print_shadow_memory(addr);
  MemoryClass mem_class = classify_memory((void *)addr);
  switch (mem_class) {
  case GLOBAL:
  case ROM:
    report_nearby_stuff_global(addr, size);
    break;
  case STACK:
    report_nearby_stuff_stack(addr);
    break;
  case HEAP:
    report_nearby_stuff_heap(addr);
    break;
  case UNKNOWN:
  case SHADOW:
    break;
  }
}
}

#define ASAN_ERROR_FUNC_FIXED(dir, is_load, size)                              \
  extern "C" void __asan_report_##dir##size(uintptr_t addr) {                  \
    report_error(addr, size, is_load, __builtin_return_address(0));            \
    abort();                                                                   \
  }                                                                            \
  extern "C" void __asan_report_##dir##size##_noabort(uintptr_t addr) {        \
    report_error(addr, size, is_load, __builtin_return_address(0));            \
  }

#define ASAN_ERROR_FUNC_VAR(dir, is_load)                                      \
  extern "C" void __asan_report_##dir##_n(uintptr_t addr, size_t size) {       \
    report_error(addr, size, is_load, __builtin_return_address(0));            \
    abort();                                                                   \
  }                                                                            \
  extern "C" void __asan_report_##dir##_n_noabort(uintptr_t addr,              \
                                                  size_t size) {               \
    report_error(addr, size, is_load, __builtin_return_address(0));            \
  }

ASAN_ERROR_FUNC_FIXED(load,  true,  1)
ASAN_ERROR_FUNC_FIXED(store, false, 1)
ASAN_ERROR_FUNC_FIXED(load,  true,  2)
ASAN_ERROR_FUNC_FIXED(store, false, 2)
ASAN_ERROR_FUNC_FIXED(load,  true,  4)
ASAN_ERROR_FUNC_FIXED(store, false, 4)
ASAN_ERROR_FUNC_FIXED(load,  true,  8)
ASAN_ERROR_FUNC_FIXED(store, false, 8)
ASAN_ERROR_FUNC_VAR(load,  true)
ASAN_ERROR_FUNC_VAR(store, false)

// }}}

// {{{ Globals

// {{{ Copied from AddressSanitizer.cpp

static uint64_t getRedzoneSizeForScale(int MappingScale) {
  // Redzone used for stack and globals is at least 32 bytes.
  // For scales 6 and 7, the redzone has to be 64 and 128 bytes respectively.
  return std::max(32U, 1U << MappingScale);
}

uint64_t getMinRedzoneSizeForGlobal() {
  return getRedzoneSizeForScale(MAPPING_SCALE);
}

uint64_t getRedzoneSizeForGlobal(uint64_t SizeInBytes) {
  constexpr uint64_t kMaxRZ = 1 << 18;
  const uint64_t MinRZ = getMinRedzoneSizeForGlobal();

  uint64_t RZ = 0;
  if (SizeInBytes <= MinRZ / 2) {
    // Reduce redzone size for small size objects, e.g. int, char[1]. MinRZ is
    // at least 32 bytes, optimize when SizeInBytes is less than or equal to
    // half of MinRZ.
    RZ = MinRZ - SizeInBytes;
  } else {
    // Calculate RZ, where MinRZ <= RZ <= MaxRZ, and RZ ~ 1/4 * SizeInBytes.
    RZ = std::clamp((SizeInBytes / MinRZ / 4) * MinRZ, MinRZ, kMaxRZ);

    // Round up to multiple of MinRZ.
    if (SizeInBytes % MinRZ)
      RZ += MinRZ - (SizeInBytes % MinRZ);
  }

  assert((RZ + SizeInBytes) % MinRZ == 0);

  return RZ;
}

// }}}

#ifdef REGISTER_GLOBALS
extern "C" __attribute__((constructor(1)))
void __asan_register_globals() {
  for (__asan_global *g = &__asan_global_metadata$$Base[0];
       g < &__asan_global_metadata$$Limit; ++g) {
    size_t redzone_size = getRedzoneSizeForGlobal(g->size);
    if (g->beg < MAPPING_MIN || (g->beg + g->size + redzone_size) >= MAPPING_MAX)
      continue;
    unpoison_mem(g->beg, g->size, redzone_size, 0xf9);
  }
}

extern "C" void __asan_register_elf_globals(uintptr_t flag, uintptr_t start, uintptr_t stop) {
  if (start == 0 || stop == 0)
    return;
  __asan_global *g_start = (__asan_global *)start;
  __asan_global *g_stop = (__asan_global *)stop;
  for (__asan_global *g = g_start; g < g_stop; ++g) {
    size_t redzone_size = getRedzoneSizeForGlobal(g->size);
    if (g->beg < MAPPING_MIN || (g->beg + g->size + redzone_size) >= MAPPING_MAX)
      continue;
    unpoison_mem(g->beg, g->size, redzone_size, 0xf9);
  }
}

extern "C" void __asan_register_image_globals(uintptr_t flag) {
  __asan_register_globals();
}

extern "C" void __asan_unregister_image_globals(uintptr_t flag) {
}

extern "C" void __asan_unregister_globals(void *, unsigned) {
}
extern "C" void __asan_unregister_elf_globals(uintptr_t flag, uintptr_t start, uintptr_t stop) {
}
#endif

// }}}

// {{{ Heap

extern "C" void *__real_malloc(size_t);
extern "C" void *$Super$$malloc(size_t size) { return __real_malloc(size); }

extern "C" void *__wrap_malloc(size_t user_size) {
  size_t header_size = 8;
  size_t real_size = (user_size + header_size + 16 + 7) & ~0x7;
  void *real_allocation = __real_malloc(real_size);
  if (!real_allocation)
    return nullptr;

  void *user_ptr = (void *)((uintptr_t)real_allocation + header_size);
  *(size_t *)real_allocation = user_size;

  // Poison the whole allocation first as heap redzone (0xf0)
  poison_mem((uintptr_t)real_allocation, real_size, 0xf0);
  // Unpoison the user part
  unpoison_mem((uintptr_t)user_ptr, user_size, 0, 0);

  return user_ptr;
}
extern "C" void *$Sub$$malloc(size_t user_size) { return __wrap_malloc(user_size); }

extern "C" void __real_free(void *);
extern "C" void *$Super$$free(void *p) { __real_free(p); return nullptr; }

extern "C" void __wrap_free(void *p) {
  if (!p)
    return;
  void *real_allocation = (void *)((uintptr_t)p - 8);
  size_t user_size = *(size_t *)real_allocation;

  // Poison the user region as freed (0xfd)
  size_t real_size = (user_size + 8 + 16 + 7) & ~0x7;
  poison_mem((uintptr_t)real_allocation, real_size, 0xfd);

  __real_free(real_allocation);
}
extern "C" void $Sub$$free(void *p) { __wrap_free(p); }

// TODO: free, realloc, ...

// }}}

// {{{ Stack

extern "C" void __asan_handle_no_return() {
  // TODO un-poison stack before call to no-return function
  // Probably doesn't matter to us
  // See https://github.com/google/sanitizers/issues/37
}

// {{{ Alloca

static const size_t kAllocaRedzoneSize = 32;
static const size_t kAllocaRedzoneMask = 31UL;
const int kAsanAllocaLeftMagic = 0xca;
const int kAsanAllocaRightMagic = 0xcb;

extern "C" void __asan_alloca_poison(uintptr_t addr, uintptr_t size) {
  uintptr_t left_redzone = addr - kAllocaRedzoneSize;
  uintptr_t PartialRzAddr = addr + size;
  uintptr_t RightRzAddr = (PartialRzAddr + kAllocaRedzoneMask) & ~kAllocaRedzoneMask;
  uintptr_t PartialRzAligned = PartialRzAddr & ~(SHADOW_GRANULARITY - 1);
  size_t right_redzone_len = ((size + 31) & ~0x1f) - size + 32;
  poison_mem(left_redzone, kAllocaRedzoneSize, kAsanAllocaLeftMagic);
  poison_mem_right_redzone(addr, size, right_redzone_len, kAsanAllocaRightMagic);
}

extern "C" void __asan_allocas_unpoison(uintptr_t top, uintptr_t bottom) {
  // "top" and "bottom" are the names compiler-rt uses for these pointers, but
  // top is actually the lower-addressed one for descending stacks.
  unpoison_mem(top, bottom - top, 0, 0);
}

// {{{ Shadow of Shadow Protection

extern "C" void __asan_protect_shadow_of_shadow(uintptr_t shadow_start,
                                                uintptr_t shadow_end) {
  uintptr_t sos_start = (uintptr_t)get_shadow_addr(shadow_start);
  uintptr_t sos_end = (uintptr_t)get_shadow_addr(shadow_end);
  if (sos_end > sos_start) {
    // Pre-poison the shadow-of-shadow region with 0xff so inline checks (*S(A) != 0) naturally trap.
    poison_mem(sos_start, sos_end - sos_start, 0xff);
  }
}

// }}}

#ifdef ENABLE_MPU
#include "MPU.h"

__attribute((constructor(0)))
void setup_mpu() {
  static MPUv8M MPU((volatile unsigned *)0xe000ed90);
  MPU.addRegion(0x00000000, 0x20000000, MPUv8M::All_RO, false); // ROM
  MPU.addRegion(0x20000000, 0x40000000, MPUv8M::All_RW, false); // RAM
  MPU.addRegion(0xe0000000, 0xffffffe0, MPUv8M::All_RW, false); // System

  // Pre-poison and lock down the shadow-of-shadow region for RAM shadows
  uintptr_t shadow_start = (uintptr_t)&Image$$ER_SHADOW_1$$Base;
  uintptr_t shadow_end = (uintptr_t)&Image$$ER_SHADOW_4$$Limit;
  __asan_protect_shadow_of_shadow(shadow_start, shadow_end);
  uintptr_t sos_start = (uintptr_t)get_shadow_addr(shadow_start);
  uintptr_t sos_end = (uintptr_t)get_shadow_addr(shadow_end);
  if (sos_end > sos_start)
    MPU.addRegion(sos_start, sos_end, MPUv8M::All_RO, false); // Shadow of Shadow (RO)

  MPU.enable();
}
#endif

// {{{ Use-after-return

struct StackAllocator {
};

extern "C" {
  int __asan_option_detect_stack_use_after_return = 0;
  void __asan_init() {
#ifndef ENABLE_MPU
    __asan_protect_shadow_of_shadow((uintptr_t)&__shadow_mem_start,
                                    (uintptr_t)&__shadow_mem_end);
#endif
#ifdef REGISTER_GLOBALS
    __asan_register_globals();
#endif
  }
  void __asan_version_mismatch_check_v8() {}
  void *__asan_stack_malloc_0(size_t size) { return nullptr; }
  void *__asan_stack_malloc_1(size_t size) { return nullptr; }
  void *__asan_stack_malloc_2(size_t size) { return nullptr; }
  void *__asan_stack_malloc_3(size_t size) { return nullptr; }
  void *__asan_stack_malloc_4(size_t size) { return nullptr; }
  void *__asan_stack_malloc_5(size_t size) { return nullptr; }
  void *__asan_stack_malloc_6(size_t size) { return nullptr; }
  void *__asan_stack_malloc_7(size_t size) { return nullptr; }
  void __asan_stack_malloc_always_1(size_t size) {}
  void *__asan_memcpy(void *dest, const void *src, size_t n) { return memcpy(dest, src, n); }
  void *__asan_memset(void *s, int c, size_t n) { return memset(s, c, n); }
  void *__asan_memmove(void *dest, const void *src, size_t n) { return memcpy(dest, src, n); }
}

// }}}
