#===----------------------------------------------------------------------===//
#
# Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
#===----------------------------------------------------------------------===//

[package]
name = "benches"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
fastrand = "2.0"
spinning_top = "0.3"
flat_tlsf = { path = "../flat_tlsf" }
flat_tlsf2 = { path = "../flat_tlsf2" }
talc = { path = "../../talc/talc", default-features = false }
memory-stats = "1.2.0"
good_memory_allocator = { version = "0.1", features = ["spin", "allocator"] }
buddy-alloc = "0.6"
dlmalloc = { version = "0.2", default-features = false, features = ["global"] }
rlsf = "0.2"
mimalloc = "0.1.46"
jemallocator = "0.5.4"
pprof = { version = "0.13", features = ["flamegraph"] }
